### ISSUE TITLE
per default auf Deutsch & Theme = hell

### ISSUE THREAD

**Issue by 1uk4sh** [muccc/engelsystem#1]
aktueller default: englisch & dark ... für die Flüchtlingsprojekte sollte das auf Deutsch & hell / light

**Comment by calbrecht** [comment]
done, pull request folgt bald https://github.com/mayflower/engelsystem/pull/2

**Comment by 1uk4sh** [comment]
hab das mit #20 mal übersprungen.

**Comment by calbrecht** [comment]
:+1:
