### ISSUE TITLE
Arrival Datum rausnehmen

### ISSUE THREAD

**Issue by 1uk4sh** [muccc/engelsystem#2]
Wir haben für die Münchner Flüchtlinge keine Ankunft / Abreise.
Die Felder sollten zumindest aus der Registrierung und der normalen user-Maske raus.

**Comment by calbrecht** [comment]
hm, wäre das evt. sinnvoll nen eigenen branch für die flüchtlingsengel anzulegen? zumindest dieses issue geht wahrscheinlich voll gegen den normalgebrauch dieser applikation und am einfachsten wäre es dieses feature komplett rauszunehmen. man könnte es auch mit feature-flags versehn, aber mei ist halt auch irgendwie aufgeblasen dann. oder ist dieses repo hier eh nie zum mergen in den parent gedacht?

**Comment by calbrecht** [comment]
ist das nicht eher das an/abreise datum der helfer. könnte doch eigentlich praktisch sein wenn das umgebogen wird zu "kann helfen von/bis"?

**Comment by dl1com** [comment]
@calbrecht Ack, vll sollte man wirklich einen "refugee" branch machen,damit man mit dem eigentlichen "master" nicht durcheinander kommt. Evtl ist ja doch etwas dabei, was irgendwann mal zurueckfliessen sollen.

Und ich finde auch, dass An/Abreise fuer "kann helfen von/bis" umgebogen werden koennte, klingt sinnvoll.

**Comment by calbrecht** [comment]
Wahrscheinlich ist das halt nicht ausreichend für den Zweck. (Denke an "kann Mo,Di u. Do und Do erst ab 14.00" oder so)

**Comment by dl1com** [comment]
@calbrecht Da hast Du recht...so eine Verfuegbarkeitstabelle wird aber wsl. nicht kurzfristig implementierbar sein.
Denke aber, dass ein Datum an dem ein Helfer "herausaltert" trotzdem nicht so verkehrt ist, weil die Planer dann einen besseren Ueberblick haben, wer ueberhaupt prinzipiell noch verfuegbar waere.

**Comment by ElectricMaxxx** [comment]
fehlt jetzt hier noch was? oder close?

**Comment by calbrecht** [comment]
imho close.

**Comment by 1uk4sh** [comment]
dann close.
