### ISSUE TITLE
dev VM dazu ausliefern

### ISSUE THREAD

**Issue by ElectricMaxxx** [muccc/engelsystem#26]
Könnten wir vll schnell eine dev VM dazu bekommen? Macht den Install deutlich schneller und einfacher.

**Comment by calbrecht** [comment]
kannst du die Konfugration für https://github.com/mayflower/wasted von https://github.com/mayflower/engelsystem/pull/3 nehmen.

**Comment by ElectricMaxxx** [comment]
Soll ich es hier zum Repo hinzufügen? Oder nur für mich local?

**Comment by calbrecht** [comment]
ich weiß es auch nicht, lass es uns bei mayflower dazutun und dann kann man immer noch nen pull request stellen

**Comment by ElectricMaxxx** [comment]
passt, danke.

**Comment by fpletz** [comment]
Fixed mit #32.
