### ISSUE TITLE
simplify "Schichten" view

### ISSUE THREAD

**Issue by 1uk4sh** [muccc/engelsystem#28]
für nicht unbeding Chaos-Compatible User wäre es schön die Schichten Ansicht zu vereinfachen.

Aktuell ist zur Auswahl: Zeitfenster, Räume, Engeltypen, Belegung.

Vereinfacht: nur Zeitfenster ? und zum ausklappen / erweitern Räume, Engeltypen, Belegung

Oder andere "Einfache Ansichten" - was immer da sinn machen könnte.

**Comment by calbrecht** [comment]
Fixed in #43
