### ISSUE TITLE
Links zu Schichten wenn eingelogged

### ISSUE THREAD

**Issue by ElectricMaxxx** [muccc/engelsystem#46]
Wenn jemand eingelogged ist, sollte er aus dem Dashboard zu mehr Informationen über die gezeigten Schichten gelangen. Entweder durch Aufklappen/Overlay oder Link.

**Comment by ElectricMaxxx** [comment]
Für news dann genauso.

**Comment by s3bb3** [comment]
Könnte uns in Hamburg auch gut helfen, um schnell eine Übersicht zu bekommen, wer was machen muss.

**Comment by ElectricMaxxx** [comment]
PR ist da. Muss nur gemerged werden.
