### ISSUE TITLE
Wenn kein Schichttitel eingetragen ist sieht das im Dashboard doof aus.

### ISSUE THREAD

**Issue by calbrecht** [muccc/engelsystem#49]
- Entweder den Schichttitel als Pflichtfeld beim anlegen,
- oder was anderes im Dashboard reinschreiben, wenn der Titel leer ist

**Comment by ElectricMaxxx** [comment]
ok. Vielleicht verstehe jetzt, was du gestern meintest. Wollen wir dann evtl. den Schichttyp nehmen?

**Comment by ElectricMaxxx** [comment]
Wenn's kein anderer tut. Mach ichs heute Abend.

**Comment by calbrecht** [comment]
Ja der Schichttyp is doch eine gute Alternative. Vlt sogar mit dem Ort in Klammern.

**Comment by ElectricMaxxx** [comment]
Jup. Erlaubt schnell wiederkehrende Sachen einzutragen.
