### ISSUE TITLE
Links zu Camp / Congress Websites / Mailinglists entfernen

### ISSUE THREAD

**Issue by 1uk4sh** [muccc/engelsystem#5]
alle Links zu Websites und Mailinglists sollten entfernt bzw. durch entsprechend neue / passende ersetzt werden.

**Comment by 1uk4sh** [comment]
in templates/layout.html und in public/maintenance.html hab ich noch "Chaos-Links" entdeckt

**Comment by saerdnaer** [comment]
Gibt es eine Kontakt-Email-Adresse?

**Comment by saerdnaer** [comment]
@lhampe Kannst du den aktuellen Stand mal ausrollen, damit man mal noch besser danach suchen kann? public/maintenance.html hatte chris glaube ich schon gemacht. Ansonsten Link am besten direkt auf die Zeile...
