### ISSUE TITLE
Der Link zu FAQ im footer zeigt auf den chaos computer club

### ISSUE THREAD

**Issue by calbrecht** [muccc/engelsystem#51]
Soll wahrscheinlich nicht so sein?

**Comment by ElectricMaxxx** [comment]
Wollen wir CMS stuff administrierbar haben oder blank aus den po files?

**Comment by calbrecht** [comment]
hmm, doe aktuell verlinkten FAQs sind ziemlich viel Text...

**Comment by 1uk4sh** [comment]
Wir wollten die FAQs vorläufig im Freifunk Wiki hosten:
https://ffmuc.net/wiki/p/Engel-muenchen
Mind eine Person ist schon dran dafür eine DAU-Kompatible Anleitung Vorzubereiten.

Können wir für den Link eine Variable in der config.php schaffen?

**Comment by msquare** [comment]
Den Link zum FAQ kann man in der config.php konfigurieren.

**Comment by 1uk4sh** [comment]
richtig - hab ich bloß falsch kopiert - besser ich gleich aus

**Comment by 1uk4sh** [comment]
FAQ Link in der config nachgezogen -> close
