### ISSUE TITLE
Naming: Orte statt Räume

### ISSUE THREAD

**Issue by 1uk4sh** [muccc/engelsystem#6]
Wenn möglich statt "Räume" dem User "Orte" anzeigen.

**Comment by 1uk4sh** [comment]
@chris007de merci - Soweit ich das überblicken kann funkitoniert das einwandfrei.
einfach close, oder noch auf weiteres Feedback warten ?

**Comment by dl1com** [comment]
Close, wenns nochmal irgendwo auftaucht einfach neuen issue oder reopen
