### ISSUE TITLE
Meine Schichten 

### ISSUE THREAD

**Issue by ElectricMaxxx** [muccc/engelsystem#60]
Im eingeloggten Zustand möchte ich als Helfer schnell und unkompliziert meine eigenen Schichten auf dem Dashboard sehen.

**Comment by ruebezahl** [comment]
Wenn ich das richtig sehe, beschränkt sich das auf einen zusätzlichen prominenten Link in der oberen Leiste? Also, weil wenn man auf den Usernamen klickt, (/?p=users&action=view) kommt genau das. Ist halt etwas unintutiv.
Edit: OK, vielleicht sollte das auch der Default-View nach Login sein...

**Comment by ElectricMaxxx** [comment]
Ich fände halt ein Dashboard ohne den Bezug auf mich selbt etwas
unvollständig, wenn ich ein geloggt bin.

Am 15.09.2015 um 16:29 schrieb ruebezahl:

**Comment by ElectricMaxxx** [comment]
Und wenn wir uns hier auf "Meine nächsten Schichten" einigen?

**Comment by ruebezahl** [comment]
jo, super.

**Comment by s3bb3** [comment]
+1 aus Hamburg, steht bei uns grad ganz oben auf der Liste!

**Comment by ElectricMaxxx** [comment]
PR ist da. muss nur noch gemerged werden.
