### ISSUE TITLE
Engel die gerade arbeiten

### ISSUE THREAD

**Issue by ElectricMaxxx** [muccc/engelsystem#63]
Ich glaube die Zahl hier ist falsch oder hat ein falsches Label.

Als ich die Zahl generiert habe wurde mir gesagt "Einträge in `ShiftEntry` zählen". Nun habe ich aber festgestellt, dass die Einträge hier drinnen bleiben, auch wenn die Shifts schon abgelaufen sind.

Das heißt die Zahl der `ShiftEntry`'s ist eigentlich "Vermittelte Engel", oder?

Sollte ich hier die Zahl anpassen, dass heißt den Query auf eine Aktuelle Schichten einschränken oder den Label anpassen? 

Einer der erfahrenen engel devs @lhampe @ruebezahl eine Idee oder einen Hinweiß?

**Comment by 1uk4sh** [comment]
#68 ist gemerged.
@ElectricMaxxx können wir den Issue damit schließen?

**Comment by ElectricMaxxx** [comment]
solved by #68

**Comment by ElectricMaxxx** [comment]
:+1:
