### ISSUE TITLE
Eigene Kommunikation

### ISSUE THREAD

**Issue by ElectricMaxxx** [muccc/engelsystem#65]
Da ich heute morgen schon einen Schnell-Schuss generiert habe (Blog-Post zum Engelsystem zu früh raus gehauen), würde mich interessieren wie ich hier an dem Projekt am Ball bleibe, d.h. wie sieht die Kommunikation zum Thema Release, Gespräche mit der Stadt usw aus?
Will mich nicht einmischen nur eben wissen, wann ich was raus posaunen darf und wann nicht.
Habt ihr eine Mailing-List, IRC oder ähnliches?

@lhampe @msquare ping.

**Comment by 1uk4sh** [comment]
Hi @ElectricMaxxx ,
stehen in Kontakt mit entsprechenden Leuten. Die Lage ändert sich täglich bis stündlich. 
@ruebezahl was hattest du für einen Eindruck nach den Gesprächen gestern Abend?

Da ich Leute untern ausschließen möchte, die nicht 24x7 im IRC online sind würde ich https://engel-muc.slack.com/ Vorschlagen. @fpletz und ich können neue einladen.

@ElectricMaxxx @ruebezahl @calbrecht @chris007de @saerdnaer @feibeck @Sicaine @katrin-schneider @globin @msquare @fadenb und wen ich noch alles vergessen hab:
Lasst mir bitte eine E-Mail Adresse von euch zukommen, dann lege ich gerne einen Account an.

**Comment by 1uk4sh** [comment]
Kleiner Nachtrag: Connection via IRC oder XMPP geht damit auch - wer möchte ;)

**Comment by ElectricMaxxx** [comment]
nimm mal für mich für den Invite die mail die hinter diesem Account hängt.

**Comment by saerdnaer** [comment]
@lhampe Gute Idee. :thumbsup:

**Comment by ElectricMaxxx** [comment]
@lhampe Also einfach maximilian.berghoff@gmx.de inviten, bitte. Danke.

**Comment by lhampe** [comment]
@ElectricMaxxx solltest vor ner halben Stunde Post bekommen haben.

**Comment by ElectricMaxxx** [comment]
huch spam

**Comment by ElectricMaxxx** [comment]
Ich denke wir haben uns gefunden, und der der es will kann den hier re-open.
