### ISSUE TITLE
Dashboard ohne Registrierung

### ISSUE THREAD

**Issue by 1uk4sh** [muccc/engelsystem#8]
Nice_to_have wäre auf der Startseite ein Dashbord anzuzeigen z.B. mit: X Helfer werden noch an Tag Y benötigt

**Comment by zeidlos** [comment]
https://github.com/ccchh/angel-news-hub ist genau das!
Ein Dashboard mit den offenen Schichten der nächsten Stunden. Das Ganze funktioniert auch wunderbar aufm Smartphone.

**Comment by ElectricMaxxx** [comment]
Das heißt jetzt hier? Selber bauen?
oder das Tool nutzen?

**Comment by ElectricMaxxx** [comment]
Fixed by #39
