### ISSUE TITLE
Mobile View anlegen

### ISSUE THREAD

**Issue by 1uk4sh** [muccc/engelsystem#9]
Für die Benutzung auf Mobilgeräten (vermutlich recht großer Anteil) wäre eine Mobile Ansicht sehr hilfreich.

**Comment by dl1com** [comment]
Soweit ich das sehe sind die meisten pages mit Formularen dank bootstrap theme bereits responsive geloest.
Einzig die kalendarische Ansicht der verfuegbaren Schichten ist noch monstroes...evtl. Bedarf das fuer eine mobile Anpassung auch eines Konzepts wie man das uebersichtlich darstellen kann.

**Comment by gnomus** [comment]
Schichtansicht auf Mobile ist mit der Listenansicht auch gegeben

**Comment by ElectricMaxxx** [comment]
Sollte durch #41 erledigt sein oder?
